# Generated by Django 3.0.4 on 2020-07-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecount',
            name='liked_num',
            field=models.IntegerField(default=0),
        ),
    ]
