# Generated by Django 3.0.4 on 2020-06-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200627_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
